name: Build

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'pyproject.toml'
      - 'uv.lock'

permissions:
  contents: read

jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081 # v5
        with:
          python-version: '3.12'
      - run: uv build
